[Project 2-2] wait
ddubbu-dev/pintos-1-9th-9team pull request #26
Opened 2024-10-03 16:17 UTC by shPark95

2024-10-03 16:17 UTC, ddubbu-dev commented on include/threads/thread.h
> +// #include <synch.h>
지워주세용!

2024-10-03 16:27 UTC, ddubbu-dev requested changes
몇가지 고쳐지고 반영되면 좋을 것 같아서 제안드려요 :)
논의 필요하시면 편히 말씀주세요!

2024-10-03 16:27 UTC, ddubbu-dev commented on include/threads/thread.h
> +    int child_status;
1. [질문] `child_status` 는 뭔가요? list 외에 필요한 상태가 있나요?
2. thread가 모드에 따라 갖고 있는 멤버 변수가 다를 것 같은데 묶어놓으면 어떨까요?
   - parent 모드 : children_process, sema_wait, ... ?
   - child 모드 : c_elem, parent_fd (parent를 가리키는 포인터라면)
3. bool 타입인걸 알기위해 `is_` 를 붙이면 어떨까요~?

```suggestion
    bool is_memory_loaded;
    bool is_process_terminated;    /* Fail = -1 */
```

2024-10-03 16:27 UTC, ddubbu-dev commented on include/userprog/syscall.h
> +typedef int pid_t;
추후 common.h 로 빼서 한쪽에서 타입을 관리하면 좋겠네요. 라고 생각했는데,

https://github.com/ddubbu-dev/pintos-1-9th-9team/blob/dev/include/lib/user/syscall.h#L9

이미 정의 된 것 같아서, 해당 header file을 임포트해서 사용하면 될 것 같아요!!

2024-10-03 16:27 UTC, ddubbu-dev commented on userprog/process.c
> +        struct thread *t = list_entry(e, struct thread, elem);
elem이 아니라 c_elem에서 꺼내야하지 않아요??

```suggestion
        struct thread *t = list_entry(e, struct thread, c_elem);
```

2024-10-03 17:01 UTC, shPark95 commented on include/threads/thread.h
> +// #include <synch.h>
지웠습니당
![Uploading image.png…]()

2024-10-03 17:01 UTC, shPark95 commented on include/threads/thread.h
> +// #include <synch.h>
![image](https://github.com/user-attachments/assets/9556c7b4-0f67-42fa-a024-3bb2d0099194)
지웠습니다!

2024-10-03 17:02 UTC, shPark95 commented on include/threads/thread.h
> +// #include <synch.h>
![image](https://github.com/user-attachments/assets/893fbbd1-f3af-4c0e-806d-c0f582e20bcd)
지웠습니다!

2024-10-03 17:03 UTC, shPark95 commented on include/threads/thread.h
> +    int child_status;
수정했습니다!

2024-10-03 17:06 UTC, shPark95 commented on include/threads/thread.h
> +// #include <synch.h>
![image](https://github.com/user-attachments/assets/83839aba-c7aa-4f7e-86a5-02e7f773c65b)
지웠습니다!

2024-10-04 01:21 UTC, ddubbu-dev commented on include/userprog/syscall.h
> +typedef int pid_t;
[구두 논의]
lib/user 하위 폴더는 user program에서 사용하는 것으로 사용 불가

2024-10-04 01:22 UTC, ddubbu-dev approved these changes
수고하셨습니다 🍀

2024-10-04 02:12 UTC, merged